FROM rocm/pytorch:rocm6.2_ubuntu22.04_py3.10_pytorch_release_2.5.1

RUN pip3 install --no-cache-dir \
    overflowml[all]

# Mount HF cache: docker run -v ~/.cache/huggingface:/root/.cache/huggingface
ENV HF_HOME=/root/.cache/huggingface

ENTRYPOINT ["overflowml"]
CMD ["--help"]
